export { default as apiClient, API_BASE_URL } from './apiClient';
export { default as productoService } from './productoService';
export { categoriaService } from './categoriaService';
export { marcaService } from './marcaService';
export { authService } from './authService';
export { tecnicoService } from './tecnicoService';
export { ventaService } from './ventaService';
export { dashboardService } from './dashboardService';
export { gastoService } from './gastoService';
export { deudaService } from './deudaService';
